import 'package:tigat_mentor_app/features/courses/models/course_model.dart';

List<Course> mockPublishedCourses = [
  Course(
    id: '1',
    title: 'Advanced UI/UX Design with Flutter',
    description: 'Master the art of creating premium-feeling mobile applications.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586717791821-3f44a563de4c?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 45)),
    studentCount: 1240,
    price: 900.0,
    status: CourseStatus.published,
  ),
  Course(
    id: '2',
    title: 'Full-Stack Web Development',
    description: 'From HTML to complex backend architectures.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 30)),
    studentCount: 850,
    price: 1200.0,
    status: CourseStatus.published,
  ),
  Course(
    id: '3',
    title: 'Mobile App Marketing Strategies',
    description: 'Learn how to grow your user base exponentially.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 20)),
    studentCount: 450,
    price: 750.0,
    status: CourseStatus.published,
  ),
  Course(
    id: '4',
    title: 'Intro to Ethical Hacking',
    description: 'Protect your systems by thinking like a hacker.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 15)),
    studentCount: 300,
    price: 1100.0,
    status: CourseStatus.published,
  ),
  Course(
    id: '5',
    title: 'Product Management Masterclass',
    description: 'Bridging the gap between engineering and business.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 10)),
    studentCount: 210,
    price: 950.0,
    status: CourseStatus.published,
  ),
  Course(
    id: '6',
    title: 'Data Science with Python',
    description: 'Unlock insights from complex data sets.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bbbda536639a?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    studentCount: 150,
    price: 1300.0,
    status: CourseStatus.published,
  ),
  Course(
    id: '7',
    title: 'Artificial Intelligence Fundamentals',
    description: 'Understanding neural networks and LLMs.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
    studentCount: 80,
    price: 1500.0,
    status: CourseStatus.published,
  ),
  Course(
    id: '8',
    title: 'Graphic Design for Beginners',
    description: 'Master Photoshop, Illustrator, and Figma.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    studentCount: 50,
    price: 650.0,
    status: CourseStatus.published,
  ),
  Course(
    id: '9',
    title: 'Blockchain & Cryptography',
    description: 'Build decentralized applications for the future.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    studentCount: 30,
    price: 1400.0,
    status: CourseStatus.published,
  ),
  Course(
    id: '10',
    title: 'Startup Growth Hacking',
    description: 'Low-cost strategies to scale your business quickly.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&q=80',
    createdAt: DateTime.now(),
    studentCount: 20,
    price: 800.0,
    status: CourseStatus.published,
  ),
];

List<Course> mockDraftCourses = [
  Course(
    id: 'd1',
    title: 'Advanced Machine Learning',
    description: 'Diving deep into reinforcement learning.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1675557009475-4309313ea398?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    price: 1600.0,
    status: CourseStatus.draft,
  ),
  Course(
    id: 'd2',
    title: 'Cybersecurity Essentials',
    description: 'Protecting your digital assets in 2024.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc48?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 4)),
    price: 950.0,
    status: CourseStatus.draft,
  ),
  Course(
    id: 'd3',
    title: 'FinTech Revolution',
    description: 'How technology is reshaping finance.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611974717482-53b925b44ec9?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 3)),
    price: 1100.0,
    status: CourseStatus.draft,
  ),
  Course(
    id: 'd4',
    title: 'Social Media Management',
    description: 'Building a powerful brand presence.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 2)),
    price: 700.0,
    status: CourseStatus.draft,
  ),
  Course(
    id: 'd5',
    title: 'Entrepreneurship for Creatives',
    description: 'Turning your art into a sustainable business.',
    thumbnailUrl: 'https://images.unsplash.com/photo-1553484771-047a44eee27b?w=400&q=80',
    createdAt: DateTime.now().subtract(const Duration(days: 1)),
    price: 850.0,
    status: CourseStatus.draft,
  ),
];
